name: 🐞 Bug
description: File a bug report
title: "[BUG] your title here"
labels: ["bug: bug suspected"]
assignees:
  - AF-1
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue (open or closed) already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: markdown
  attributes:
    value: "<br><br>"
- type: checkboxes
  attributes:
    label: Check common causes of LMS (plugin) problems
    description: Please take a quick look at [**this checklist**](https://github.com/AF-1/sobras/wiki/Checklist-to-eliminate-common-causes-of-LMS-(plugin)-problems) to eliminate common causes of LMS (plugin) problems.
    options:
    - label: The list has no fix for my issue
      required: true
- type: markdown
  attributes:
    value: "<br><br>"
- type: textarea
  attributes:
    label: What happened?
    description: A concise description of what you're experiencing
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br><br>"
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br><br>"
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error...
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br><br>"
- type: input
  attributes:
    label: LMS version
    description: What version of LMS are you running?
    placeholder: "Example: 9.0.1"
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br>"
- type: input
  attributes:
    label: Applet version
    description: What version of the applet are you running?
    placeholder: "Example: 1.0.3"
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br>"
- type: input
  attributes:
    label: "Your OS (incl. version)"
    description: What OS (incl. version) is jivelite running on?
    placeholder: "Examples: piCorePlayer 9.2, SB Touch Firmware 8.5.1, SqueezePlay 8.4.1r1498 on macOS 15.3"
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br>"
- type: textarea
  attributes:
    label: Environment
    description: |
      Go to *LMS settings > Information* and copy/paste the information for *Lyrion Music Server Status* and *Perl and Module Versions* here.
      And a **list of installed plugins** (incl. version numbers).
    placeholder: |
      Lyrion Music Server Status: …

      Perl and Module Versions: …

      List of installed plugins: …
    render: markdown
  validations:
    required: false
- type: markdown
  attributes:
    value: "<br><br>"
- type: checkboxes
  attributes:
    label: Is there relevant output for this?
    description: |
     * Add relevant (error) messages from the **LMS server log** (file path at the bottom of *LMS settings* > *Information*). Use the **time stamps** in the log to find messages created around the time your problem occurred.
     * If there are no server log error messages, set the **debug level for this plugin** to **Info** in *LMS settings* > *Advanced* > *Logging*, **reproduce the problem** and **check the server log** again. If there's still nothing, **repeat** this step with the debug level set to **Debug**.
     * Please check the log file on the device that runs the applet (before rebooting):
       * piCorePlayer jivelite log file path: `/var/log/pcp_jivelite.log`
       * SB Touch / SB Radio log file path: `/var/log/messages`
    options:
    - label: I have searched the log files
      required: true
- type: textarea
  attributes:
    label: Relevant log output
    description: "Please copy and paste any relevant log output here. This will be automatically formatted into code, so no need for backticks.<br>📎 Alternatively, **attach** the complete log **files** (see *Anything else* below)."
    render: shell
- type: markdown
  attributes:
    value: "<br><br>"
- type: textarea
  attributes:
    label: Anything else? 📎 Attachments etc.
    description: |
      Screenshots? Log files? Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images (screenshots) or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: markdown
  attributes:
    value: "<br><br>"
- type: markdown
  attributes:
    value: |
      ## ⭐ Help others discover this project
      If you find this project useful, giving it a [**star**](https://github.com/AF-1/jivelite-darkflatskin#-help-others-discover-this-project) is a great way to show your support and help others discover it. Thank you.
- type: markdown
  attributes:
    value: "<br><br>"
